-- TNPSC Group 1 seed
-- Safe to run multiple times (ON CONFLICT DO NOTHING / idempotent checks)

DO $$
DECLARE
  v_subject_id UUID;
BEGIN
  -- Insert subject
  INSERT INTO subjects (name, icon, exam_category)
  VALUES ('TNPSC Group 1', '📋', 'TNPSC')
  ON CONFLICT (name) DO NOTHING;

  SELECT id INTO v_subject_id FROM subjects WHERE name = 'TNPSC Group 1';

  -- Insert Preliminary Exam chapters (Units I–X) only if they don't already exist
  INSERT INTO chapters (subject_id, title, order_index, content_text, is_approved)
  SELECT v_subject_id, t.title, t.order_index, t.content_text, true
  FROM (VALUES
    (1,  'Prelim — Unit I: General Science',
     'Scientific Knowledge and Scientific Temper. Power of Reasoning. Rote Learning vs Conceptual Learning. Science as a tool to understand the past, present and future. Nature of Universe, General Scientific Laws, Mechanics, Properties of Matter, Force, Motion and Energy. Everyday application of Mechanics, Electricity and Magnetism, Light, Sound, Heat, Nuclear Physics, Laser, Electronics and Communications. Elements and Compounds, Acids, Bases, Salts, Petroleum Products, Fertilisers, Pesticides. Main concepts of Life Science, Classification of Living Organisms, Evolution, Genetics, Physiology, Nutrition, Health and Hygiene, Human Diseases. Environment and Ecology.'),
    (2,  'Prelim — Unit II: Current Events',
     'History: Latest diary of events, National symbols, Profile of States, Eminent personalities and places in news, Sports, Books and authors. Polity: Political parties and political system in India, Public awareness and General administration, Welfare oriented Government schemes and their utility, Problems in Public Delivery Systems. Geography: Geographical landmarks. Economics: Current socio-economic issues. Science: Latest inventions in Science and Technology. Prominent Personalities in various spheres: Arts, Science, Literature and Philosophy.'),
    (3,  'Prelim — Unit III: Geography of India',
     'Location, Physical features, Monsoon, Rainfall, Weather and Climate, Water Resources, Rivers in India, Soil, Minerals and Natural Resources, Forest and Wildlife, Agricultural pattern. Transport and Communication. Social Geography: Population density and distribution, Racial and Linguistic Groups, Major Tribes. Natural calamity, Disaster Management, Environmental pollution: Reasons and preventive measures, Climate change, Green energy.'),
    (4,  'Prelim — Unit IV: History and Culture of India',
     'Indus Valley Civilization, Guptas, Delhi Sultans, Mughals and Marathas, Age of Vijayanagaram and Bahmani Kingdoms, South Indian History. Change and Continuity in the Socio-Cultural History of India. Characteristics of Indian Culture, Unity in Diversity: Race, Language, Custom. India as a Secular State, Social Harmony.'),
    (5,  'Prelim — Unit V: Indian Polity',
     'Constitution of India, Preamble to the Constitution, Salient features of the Constitution, Union, State and Union Territory. Citizenship, Fundamental Rights, Fundamental Duties, Directive Principles of State Policy. Union Executive, Union Legislature, State Executive, State Legislature, Local Governments, Panchayat Raj. Spirit of Federalism: Centre-State Relationships. Election, Judiciary in India, Rule of Law. Corruption in Public Life, Anti-corruption measures, Lokpal and Lok Ayukta, Right to Information, Empowerment of Women, Consumer Protection Forums, Human Rights Charter.'),
    (6,  'Prelim — Unit VI: Indian Economy',
     'Nature of Indian Economy, Five year plan models, Planning Commission and NITI Aayog. Sources of revenue, Reserve Bank of India, Fiscal Policy and Monetary Policy, Finance Commission, Resource sharing between Union and State Governments, Goods and Services Tax. Structure of Indian Economy and Employment Generation, Land Reforms and Agriculture, Application of Science and Technology in Agriculture, Industrial growth, Rural Welfare Oriented Programmes, Social Problems: Population, Education, Health, Employment, Poverty.'),
    (7,  'Prelim — Unit VII: Indian National Movement',
     'National Renaissance, Early uprising against British rule, Indian National Congress, Emergence of leaders: B.R.Ambedkar, Bhagat Singh, Bharathiar, V.O.Chidambaranar, Jawaharlal Nehru, Kamarajar, Mahatma Gandhi, Maulana Abul Kalam Azad, Thanthai Periyar, Rajaji, Subash Chandra Bose, Rabindranath Tagore and others. Different modes of Agitation: Growth of Satyagraha and Militant Movements. Communalism and Partition.'),
    (8,  'Prelim — Unit VIII: History, Culture & Socio-Political Movements in Tamil Nadu',
     'History of Tamil Society, related Archaeological discoveries, Tamil Literature from Sangam Age till contemporary times. Thirukkural: Significance as a Secular Literature, Relevance to Everyday Life, Impact on Humanity, Universal Values including Equality and Humanism, Relevance to Socio-Politico-Economic affairs, Philosophical content. Role of Tamil Nadu in freedom struggle, Early agitations against British Rule, Role of women in freedom struggle. Evolution of 19th and 20th Century Socio-Political Movements in Tamil Nadu: Justice Party, Growth of Rationalism, Self Respect Movement, Dravidian Movement, Contributions of Thanthai Periyar and Perarignar Anna.'),
    (9,  'Prelim — Unit IX: Development Administration in Tamil Nadu',
     'Human Development Indicators in Tamil Nadu and comparative assessment across the Country. Impact of Social Reform Movements in the Socio-Economic Development of Tamil Nadu. Political parties and Welfare schemes for various sections of people, Rationale behind Reservation Policy and access to Social Resources, Economic trends in Tamil Nadu, Role and impact of social welfare schemes in the Socio-Economic Development of Tamil Nadu. Social Justice and Social Harmony as the Cornerstones of Socio-Economic Development. Education and Health Systems in Tamil Nadu. Geography of Tamil Nadu and its impact on Economic growth. Achievements of Tamil Nadu in various fields. e-Governance in Tamil Nadu.'),
    (10, 'Prelim — Unit X: Aptitude & Mental Ability',
     'Simplification, Percentage, HCF, LCM. Ratio and Proportion. Simple interest, Compound interest, Area, Volume, Time and Work. Logical Reasoning, Puzzles, Dice, Visual Reasoning, Alphanumeric Reasoning, Number Series.')
  ) AS t(order_index, title, content_text)
  WHERE NOT EXISTS (
    SELECT 1 FROM chapters WHERE subject_id = v_subject_id AND title = t.title
  );

  -- Main Exam chapters
  INSERT INTO chapters (subject_id, title, order_index, content_text, is_approved)
  SELECT v_subject_id, t.title, t.order_index, t.content_text, true
  FROM (VALUES
    (11, 'Main — Paper I: Compulsory Tamil Language (SSLC Standard)',
     'Translation from Tamil to English and English to Tamil. Precis Writing. Comprehension. Expansion from Brief Notes. Essay writing on Thirukkural topics. Official Letter Writing. Tamil Language Knowledge. This is a qualifying paper at SSLC standard; marks are not counted for ranking.'),
    (12, 'Main — Paper II, Unit I: Modern History of India and Indian Culture',
     'Advent of European invasion, Expansion and consolidation of British rule, Early uprisings, 1857 Revolt, Indian National Congress, Growth of militant movements, National leaders including Gandhi, Nehru, Tagore, Netaji, Ambedkar, Patel, Maulana Abul Kalam Azad. Era of Acts and Pacts, Second World War and final phase of freedom struggle, Communalism and Partition. Effect of British rule on socio-economic factors, National renaissance, Socio-religious reform movements. India since independence, Characteristics of Indian culture, Unity in diversity, India as a secular state, Role of Tamil Nadu in freedom struggle. Latest diary of events National and International, National symbols, Sports, Books, Authors, Awards.'),
    (13, 'Main — Paper II, Unit II: Social Issues in India and Tamil Nadu',
     'Population Explosion, Unemployment, Child Abuse and Child Labour, Poverty, Rural and Urban Sanitation, Illiteracy. Women Empowerment, Role of Government, Social injustice to Women, Domestic violence, Dowry, Sexual assault, Role of women''s organisations. Social changes in India, Urbanization and its impact, Violence, Terrorism and Communal violence, Regional Disparities, Problems of Minorities, Human Rights. Education, Social Development, Community Development Programmes, Employment Guarantee Schemes, Self Employment and Entrepreneurship, Role of NGOs, Government Policy on Health, Welfare Schemes for vulnerable sections.'),
    (14, 'Main — Paper II, Unit III: General Aptitude & Mental Ability (SSLC Standard)',
     'Data collection, compilation and presentation: Tables, Graphs, Diagrams. Percentage, HCF, LCM, Ratio and Proportion, Simple and Compound Interest, Area, Volume, Time and Work, Probability. Information Technology, Basic terms, Communications, Application of ICT, Decision making and problem solving, Basics of Computers and Computer terminology.'),
    (15, 'Main — Paper III, Unit I: Indian Polity and Emerging Political Trends',
     'Constitution of India: Historical background, Preamble, Fundamental Rights and Duties, DPSP, Schedules. Union Executive: President, Vice-President, Prime Minister, Council of Ministers, Attorney General. Union Legislature: Parliament, Lok Sabha, Rajya Sabha. Union Judiciary: Supreme Court, Judicial Review. State Executive, State Legislature, State Judiciary. Local Government: 73rd and 74th Constitutional Amendment Act, 1992. Federalism: Centre-State Relations. Civil Services, Official Language, Amendments, Art 370. Political Parties, Pressure Groups, NGOs. Anti-Corruption measures: CVC, Lok Adalats, RTI Act. India''s Foreign Policy, Nuclear Policy, Indian Diaspora.'),
    (16, 'Main — Paper III, Unit II: Role and Impact of Science and Technology in Development of India',
     'Science and Technology, Role, Achievements and Developments, Applications in everyday life, Energy Conventional and Non-conventional, Oil exploration, Defence Research Organisations. Advancements in IT, Space, Computers, Robotics, Nano-Technology, Mobile Communication, Remote sensing. Health and hygiene, Human diseases, Prevention and remedies, Communicable and Non-communicable diseases, Genetic Engineering, Organ transplantation, Stem cell Technology, Medical Tourism. Achievements of Indians in Science and Technology, Latest inventions.'),
    (17, 'Main — Paper III, Unit III: Tamil Society — Its Culture and Heritage',
     'Tamil Society: Origin and expansion. Art and Culture: Literature, Music, Film, Drama, Architecture, Sculpture, Paintings and Folk Arts. Socio-economic history of Tamil Nadu from Sangam age till date. Growth of Rationalist and Dravidian movements in Tamil Nadu. Social and cultural life of contemporary Tamils: Caste, Religion, Women, Politics, Education, Economy, Trade and relationship with other countries. Tamil and other Disciplines: Mass Media, Computer.'),
    (18, 'Main — Paper IV, Unit I: Geography of India with Special Reference to Tamil Nadu',
     'Location, Physical features, Major Rivers, Weather and Climate, Monsoon, Rainfall, Natural resources: Soil, Water, Forest, Minerals, Wildlife, Agricultural pattern, Livestock, Fisheries, Industries. Social-Cultural geography, Population Growth, Density and Distribution, Racial, linguistic and major tribes. Oceanography: Bottom relief features of Indian Ocean, Arabian Sea and Bay of Bengal. Geospatial Technology: GIS and GNSS. Map: Geographical landmarks, India and its neighbours.'),
    (19, 'Main — Paper IV, Unit II: Environment, Biodiversity and Disaster Management',
     'Ecology: Structure and function of Ecosystem, Ecological succession, Biodiversity conservation, Types, Hot Spots in India. In situ and Ex situ conservation. Roles of CITES, IUCN and Convention on Biological Diversity. Environmental Pollution and Management: Air, Water, Soil, Thermal and Noise pollution. Solid and Hazardous waste management. Environmental Impact Assessment. Climate Change: Global Environmental Issues, Changes in monsoon pattern, Environmental consequences and mitigation measures, Clean and Green Energy. Environmental Laws, Policies and Treaties, Natural calamities and Disaster Management.'),
    (20, 'Main — Paper IV, Unit III: Indian Economy — Current Economic Trends',
     'Features of Indian Economy, Demographical profile, National Income, Capital formation, NEP, NITI AYOG. Agriculture: Land reforms, Green Revolution, Price Policy, PDS, Subsidy, Food Security, Agricultural Marketing, Crop Insurance, Rural credit, WTO and Agriculture. Industry: Growth, Policy, Public sector, Privatisation, Liberalization, PPP, SEZs, MSMEs, Make in India. Infrastructure: Transport, Energy, Power, Communication, R&D. Banking and Finance: Central Bank, Commercial Bank, Stock Market, Monetary Policy, RBI. Public Finance: Revenue, GST, Fiscal Policy, Finance Commission. Poverty, MGNREGA, Unemployment, Inflation, Gender issues. India''s Foreign Trade: BOP, FDI, Globalization, Global economic crisis. International Agencies: IMF, World Bank, BRICS, SAARC, ASEAN. Tamil Nadu Economy: GSDP, Agriculture, Industry, SHGs, Rural Women empowerment, Rural poverty, Environmental issues.')
  ) AS t(order_index, title, content_text)
  WHERE NOT EXISTS (
    SELECT 1 FROM chapters WHERE subject_id = v_subject_id AND title = t.title
  );

  -- Backfill Tamil content text (idempotent: only sets where NULL)
  UPDATE chapters c SET content_text_tamil = t.ct
  FROM (VALUES
    ('Prelim — Unit I: General Science',
     'அறிவியல் அறிவு மற்றும் அறிவியல் சிந்தனை. சிந்திக்கும் திறன். மனப்பாட கல்வி மற்றும் கருத்துரீதியான கல்வி. கடந்த காலம், நிகழ் காலம் மற்றும் எதிர்காலத்தை புரிந்துகொள்ள அறிவியல் ஒரு கருவியாகும். பிரபஞ்சத்தின் தன்மை, பொது அறிவியல் விதிகள், இயக்கவியல், பொருளின் பண்புகள், விசை, இயக்கம் மற்றும் ஆற்றல். இயக்கவியல், மின்சாரம் மற்றும் காந்தவியல், ஒளி, ஒலி, வெப்பம், அணு இயற்பியல், லேசர், மின்னணுவியல் மற்றும் தொடர்பியல் ஆகியவற்றின் அன்றாட பயன்பாடு. தனிமங்கள் மற்றும் சேர்மங்கள், அமிலங்கள், காரங்கள், உப்புகள், பெட்ரோலியம் தயாரிப்புகள், உரங்கள், பூச்சிக்கொல்லிகள். உயிரியல் அறிவியலின் முக்கிய கருத்துகள், உயிரினங்களின் வகைப்பாடு, பரிணாமம், மரபியல், உடலியல், ஊட்டச்சத்து, சுகாதாரம் மற்றும் ஆரோக்கியம், மனித நோய்கள். சுற்றுச்சூழல் மற்றும் சூழலியல்.'),
    ('Prelim — Unit II: Current Events',
     'வரலாறு: சமீபத்திய நிகழ்வுகளின் குறிப்பேடு, தேசிய சின்னங்கள், மாநில சுயவிவரங்கள், தகவல்களில் முக்கிய ஆளுமைகள் மற்றும் இடங்கள், விளையாட்டு, புத்தகங்கள் மற்றும் ஆசிரியர்கள். அரசியல்: இந்தியாவில் அரசியல் கட்சிகள் மற்றும் அரசியல் அமைப்பு, பொது விழிப்புணர்வு மற்றும் பொது நிர்வாகம், நலன் சார்ந்த அரசாங்க திட்டங்கள் மற்றும் அவற்றின் பயன்பாடு, பொது விநியோக அமைப்புகளில் உள்ள சிக்கல்கள். புவியியல்: புவியியல் அடையாளங்கள். பொருளாதாரம்: தற்போதைய சமூக-பொருளாதார பிரச்சினைகள். அறிவியல்: அறிவியல் மற்றும் தொழில்நுட்பத்தில் சமீபத்திய கண்டுபிடிப்புகள். பல்வேறு துறைகளில் முக்கிய ஆளுமைகள்: கலை, அறிவியல், இலக்கியம் மற்றும் தத்துவம்.'),
    ('Prelim — Unit III: Geography of India',
     'இருப்பிடம், இயற்பியல் அம்சங்கள், பருவமழை, மழையளவு, வானிலை மற்றும் காலநிலை, நீர் வளங்கள், இந்தியாவில் ஆறுகள், மண், தாதுக்கள் மற்றும் இயற்கை வளங்கள், காடுகள் மற்றும் வனவிலங்குகள், வேளாண் முறைகள். போக்குவரத்து மற்றும் தொடர்பு. சமூக புவியியல்: மக்கள்தொகை அடர்த்தி மற்றும் பரவல், இன மற்றும் மொழியியல் குழுக்கள், முக்கிய பழங்குடியினர். இயற்கை பேரழிவு, பேரிடர் மேலாண்மை, சுற்றுச்சூழல் மாசு: காரணங்கள் மற்றும் தடுப்பு நடவடிக்கைகள், காலநிலை மாற்றம், பசுமை ஆற்றல்.'),
    ('Prelim — Unit IV: History and Culture of India',
     'சிந்து சமவெளி நாகரிகம், குப்தர்கள், டெல்லி சுல்தான்கள், முகலாயர்கள் மற்றும் மராட்டியர்கள், விஜயநகர மற்றும் பாமினி அரசுகளின் காலம், தென்னிந்திய வரலாறு. இந்தியாவின் சமூக-கலாச்சார வரலாற்றில் மாற்றமும் தொடர்ச்சியும். இந்திய கலாச்சாரத்தின் பண்புகள், பன்முகத்தன்மையில் ஒற்றுமை: இனம், மொழி, வழக்கம். இந்தியா ஒரு மதச்சார்பற்ற நாடாக, சமூக நல்லிணக்கம்.'),
    ('Prelim — Unit V: Indian Polity',
     'இந்திய அரசியலமைப்பு, அரசியலமைப்பின் முன்னுரை, அரசியலமைப்பின் முக்கிய அம்சங்கள், ஒன்றியம், மாநிலம் மற்றும் யூனியன் பிரதேசம். குடியுரிமை, அடிப்படை உரிமைகள், அடிப்படை கடமைகள், மாநில கொள்கையின் வழிகாட்டு நெறிமுறைகள். ஒன்றிய நிர்வாகம், ஒன்றிய சட்டமன்றம், மாநில நிர்வாகம், மாநில சட்டமன்றம், உள்ளாட்சி அமைப்புகள், பஞ்சாயத்து ராஜ். கூட்டாட்சியின் சாரம்: மத்திய-மாநில உறவுகள். தேர்தல், இந்தியாவில் நீதித்துறை, சட்டத்தின் ஆட்சி. பொது வாழ்வில் ஊழல், ஊழல் எதிர்ப்பு நடவடிக்கைகள், லோக்பால் மற்றும் லோக் ஆயுக்தா, தகவல் அறியும் உரிமை, பெண்கள் வலிமைப்படுத்தல், நுகர்வோர் பாதுகாப்பு மன்றங்கள், மனித உரிமைகள் சாசனம்.'),
    ('Prelim — Unit VI: Indian Economy',
     'இந்திய பொருளாதாரத்தின் தன்மை, ஐந்தாண்டு திட்ட மாதிரிகள், திட்டக் குழு மற்றும் நீதி ஆயோக். வருவாய் ஆதாரங்கள், இந்திய ரிசர்வ் வங்கி, நிதி கொள்கை மற்றும் பணவியல் கொள்கை, நிதி ஆணையம், மத்திய மற்றும் மாநில அரசுகளுக்கிடையேயான வளப்பகிர்வு, சரக்கு மற்றும் சேவை வரி. இந்திய பொருளாதாரத்தின் அமைப்பு மற்றும் வேலை வாய்ப்பு உருவாக்கம், நில சீர்திருத்தங்கள் மற்றும் வேளாண்மை, வேளாண்மையில் அறிவியல் மற்றும் தொழில்நுட்பத்தின் பயன்பாடு, தொழில்துறை வளர்ச்சி, கிராம நல நோக்கு திட்டங்கள், சமூக சிக்கல்கள்: மக்கள்தொகை, கல்வி, சுகாதாரம், வேலைவாய்ப்பு, வறுமை.'),
    ('Prelim — Unit VII: Indian National Movement',
     'தேசிய மறுமலர்ச்சி, ஆங்கிலேயர் ஆட்சிக்கு எதிரான ஆரம்பகால எழுச்சி, இந்திய தேசிய காங்கிரஸ், தலைவர்களின் தோற்றம்: பி.ஆர்.அம்பேத்கர், பகத் சிங், பாரதியார், வ.உ.சிதம்பரனார், ஜவஹர்லால் நேரு, காமராஜர், மகாத்மா காந்தி, மௌலானா அபுல் கலாம் ஆசாத், தந்தை பெரியார், ராஜாஜி, சுபாஷ் சந்திர போஸ், ரவீந்திரநாத் தாகூர் மற்றும் பிறர். போராட்டத்தின் வெவ்வேறு முறைகள்: சத்தியாகிரகம் மற்றும் தீவிர இயக்கங்களின் வளர்ச்சி. வகுப்புவாதம் மற்றும் பிரிவினை.'),
    ('Prelim — Unit VIII: History, Culture & Socio-Political Movements in Tamil Nadu',
     'தமிழ் சமூகத்தின் வரலாறு, தொடர்புடைய தொல்லியல் கண்டுபிடிப்புகள், சங்க காலம் முதல் இக்காலம் வரையிலான தமிழ் இலக்கியம். திருக்குறள்: மதச்சார்பற்ற இலக்கியமாக அதன் முக்கியத்துவம், அன்றாட வாழ்வில் பொருத்தப்பாடு, மனிதகுலத்தில் தாக்கம், சமத்துவம் மற்றும் மனிதநேயம் உள்ளிட்ட உலகளாவிய மதிப்புகள், சமூக-அரசியல்-பொருளாதார விவகாரங்களில் பொருத்தப்பாடு, தத்துவ உள்ளடக்கம். விடுதலைப் போராட்டத்தில் தமிழ்நாட்டின் பங்கு, ஆங்கிலேயர் ஆட்சிக்கு எதிரான ஆரம்பகால போராட்டங்கள், விடுதலைப் போராட்டத்தில் பெண்களின் பங்கு. தமிழ்நாட்டில் 19ஆம் மற்றும் 20ஆம் நூற்றாண்டு சமூக-அரசியல் இயக்கங்களின் பரிணாமம்: நீதிக் கட்சி, பகுத்தறிவுவாதத்தின் வளர்ச்சி, சுயமரியாதை இயக்கம், திராவிட இயக்கம், தந்தை பெரியார் மற்றும் பேரறிஞர் அண்ணாவின் பங்களிப்புகள்.'),
    ('Prelim — Unit IX: Development Administration in Tamil Nadu',
     'தமிழ்நாட்டில் மனித வளர்ச்சி குறியீடுகள் மற்றும் நாடு முழுவதும் ஒப்பீட்டு மதிப்பீடு. தமிழ்நாட்டின் சமூக-பொருளாதார வளர்ச்சியில் சமூக சீர்திருத்த இயக்கங்களின் தாக்கம். மக்களின் பல்வேறு பிரிவுகளுக்கான அரசியல் கட்சிகள் மற்றும் நல திட்டங்கள், இட ஒதுக்கீட்டுக் கொள்கைக்கு பின்னுள்ள நியாயாயதர்க்கம் மற்றும் சமூக வளங்களுக்கான அணுகல், தமிழ்நாட்டில் பொருளாதார போக்குகள், தமிழ்நாட்டின் சமூக-பொருளாதார வளர்ச்சியில் சமூக நல திட்டங்களின் பங்கு மற்றும் தாக்கம். சமூக-பொருளாதார வளர்ச்சியின் அடிக்கல்லாக சமூக நீதி மற்றும் சமூக நல்லிணக்கம். தமிழ்நாட்டில் கல்வி மற்றும் சுகாதார அமைப்புகள். தமிழ்நாட்டின் புவியியல் மற்றும் பொருளாதார வளர்ச்சியில் அதன் தாக்கம். பல்வேறு துறைகளில் தமிழ்நாட்டின் சாதனைகள். தமிழ்நாட்டில் மின்-நிர்வாகம்.'),
    ('Prelim — Unit X: Aptitude & Mental Ability',
     'எளிமைப்படுத்தல், சதவீதம், மி.பொ.வ (HCF), மி.சொ.ம (LCM). விகிதம் மற்றும் விகிதாச்சாரம். தனி வட்டி, கூட்டு வட்டி, பரப்பு, கன அளவு, நேரம் மற்றும் வேலை. தர்க்க சிந்தனை, புதிர்கள், பகடை, காட்சி சிந்தனை, எண் மற்றும் எழுத்து சிந்தனை, எண் தொடர்கள்.'),
    ('Main — Paper I: Compulsory Tamil Language (SSLC Standard)',
     'தமிழிலிருந்து ஆங்கிலத்திற்கும் ஆங்கிலத்திலிருந்து தமிழிற்கும் மொழிபெயர்ப்பு. சுருக்கெழுத்து. புரிந்துகொள்ளல். சுருக்கமான குறிப்புகளிலிருந்து விரிவாக்கம். திருக்குறள் தலைப்புகளில் கட்டுரை எழுதல். அலுவல் கடிதம் எழுதல். தமிழ் மொழி அறிவு. இது SSLC தரத்தில் ஒரு தகுதி தாள்; தரவரிசைக்கு மதிப்பெண்கள் கணக்கிடப்படுவதில்லை.'),
    ('Main — Paper II, Unit I: Modern History of India and Indian Culture',
     'ஐரோப்பிய படையெடுப்பின் வருகை, ஆங்கிலேயர் ஆட்சியின் விரிவாக்கம் மற்றும் ஒருங்கிணைப்பு, ஆரம்பகால எழுச்சிகள், 1857 புரட்சி, இந்திய தேசிய காங்கிரஸ், தீவிர இயக்கங்களின் வளர்ச்சி, காந்தி, நேரு, தாகூர், நேதாஜி, அம்பேத்கர், படேல், மௌலானா அபுல் கலாம் ஆசாத் உள்ளிட்ட தேசிய தலைவர்கள். சட்டங்கள் மற்றும் ஒப்பந்தங்களின் சகாப்தம், இரண்டாம் உலகப் போர் மற்றும் விடுதலை போராட்டத்தின் இறுதிக் கட்டம், வகுப்புவாதம் மற்றும் பிரிவினை. சமூக-பொருளாதார காரணிகளில் ஆங்கிலேயர் ஆட்சியின் விளைவு, தேசிய மறுமலர்ச்சி, சமூக-மத சீர்திருத்த இயக்கங்கள். சுதந்திரத்திற்குப் பிறகு இந்தியா, இந்திய கலாச்சாரத்தின் பண்புகள், பன்முகத்தன்மையில் ஒற்றுமை, இந்தியா ஒரு மதச்சார்பற்ற நாடாக, விடுதலைப் போராட்டத்தில் தமிழ்நாட்டின் பங்கு. சமீபத்திய தேசிய மற்றும் சர்வதேச நிகழ்வுகள், தேசிய சின்னங்கள், விளையாட்டு, புத்தகங்கள், ஆசிரியர்கள், விருதுகள்.'),
    ('Main — Paper II, Unit II: Social Issues in India and Tamil Nadu',
     'மக்கள்தொகை வெடிப்பு, வேலையின்மை, குழந்தை துஷ்பிரயோகம் மற்றும் குழந்தை தொழிலாளர், வறுமை, கிராமப்புற மற்றும் நகர்ப்புற சுகாதாரம், கல்வியறிவின்மை. பெண்கள் வலிமைப்படுத்தல், அரசாங்கத்தின் பங்கு, பெண்களுக்கு சமூக அநீதி, குடும்ப வன்முறை, வரதட்சணை, பாலியல் வன்கொடுமை, பெண்கள் அமைப்புகளின் பங்கு. இந்தியாவில் சமூக மாற்றங்கள், நகரமயமாதல் மற்றும் அதன் தாக்கம், வன்முறை, பயங்கரவாதம் மற்றும் வகுப்பு வன்முறை, பிராந்திய ஏற்றத்தாழ்வுகள், சிறுபான்மையினரின் சிக்கல்கள், மனித உரிமைகள். கல்வி, சமூக வளர்ச்சி, சமூக மேம்பாட்டு திட்டங்கள், வேலை உத்தரவாதத் திட்டங்கள், சுய வேலைவாய்ப்பு மற்றும் தொழில்முனைவு, அரசு சாரா நிறுவனங்களின் பங்கு, சுகாதாரம் குறித்த அரசாங்க கொள்கை, பாதிக்கப்படக்கூடிய பிரிவினருக்கான நல திட்டங்கள்.'),
    ('Main — Paper II, Unit III: General Aptitude & Mental Ability (SSLC Standard)',
     'தரவு சேகரிப்பு, தொகுப்பு மற்றும் வழங்கல்: அட்டவணைகள், வரைபடங்கள், விளக்கப்படங்கள். சதவீதம், மி.பொ.வ, மி.சொ.ம, விகிதம் மற்றும் விகிதாச்சாரம், தனி மற்றும் கூட்டு வட்டி, பரப்பு, கன அளவு, நேரம் மற்றும் வேலை, நிகழ்தகவு. தகவல் தொழில்நுட்பம், அடிப்படை சொற்கள், தொடர்பு, ICT பயன்பாடு, முடிவெடுத்தல் மற்றும் சிக்கல் தீர்க்கல், கணினியின் அடிப்படைகள் மற்றும் கணினி சொற்கள்.'),
    ('Main — Paper III, Unit I: Indian Polity and Emerging Political Trends',
     'இந்திய அரசியலமைப்பு: வரலாற்று பின்னணி, முன்னுரை, அடிப்படை உரிமைகள் மற்றும் கடமைகள், DPSP, அட்டவணைகள். ஒன்றிய நிர்வாகம்: ஜனாதிபதி, துணை ஜனாதிபதி, பிரதமர், அமைச்சரவை, அட்டர்னி ஜெனரல். ஒன்றிய சட்டமன்றம்: பாராளுமன்றம், லோக்சபா, ராஜ்யசபா. ஒன்றிய நீதித்துறை: உச்சநீதிமன்றம், நீதி மறுஆய்வு. மாநில நிர்வாகம், மாநில சட்டமன்றம், மாநில நீதித்துறை. உள்ளாட்சி: 73வது மற்றும் 74வது அரசியலமைப்பு திருத்தச் சட்டம், 1992. கூட்டாட்சி: மத்திய-மாநில உறவுகள். சிவில் சேவைகள், அலுவல் மொழி, திருத்தங்கள், சட்டப்பிரிவு 370. அரசியல் கட்சிகள், அழுத்தக் குழுக்கள், அரசு சாரா நிறுவனங்கள். ஊழல் எதிர்ப்பு நடவடிக்கைகள்: CVC, லோக் அதாலத்கள், RTI சட்டம். இந்தியாவின் வெளியுறவுக் கொள்கை, அணு கொள்கை, இந்திய புலம்பெயர் சமூகம்.'),
    ('Main — Paper III, Unit II: Role and Impact of Science and Technology in Development of India',
     'அறிவியல் மற்றும் தொழில்நுட்பம், பங்கு, சாதனைகள் மற்றும் முன்னேற்றங்கள், அன்றாட வாழ்வில் பயன்பாடுகள், பாரம்பரிய மற்றும் மாற்று ஆற்றல், எண்ணெய் ஆய்வு, பாதுகாப்பு ஆராய்ச்சி நிறுவனங்கள். IT, விண்வெளி, கணினிகள், ரோபோட்டிக்ஸ், நானோ தொழில்நுட்பம், மொபைல் தொடர்பு, தொலை உணர்வு ஆகியவற்றில் முன்னேற்றங்கள். சுகாதாரம் மற்றும் ஆரோக்கியம், மனித நோய்கள், தடுப்பு மற்றும் தீர்வுகள், தொற்று மற்றும் தொற்றா நோய்கள், மரபியல் பொறியியல், உறுப்பு மாற்று அறுவை சிகிச்சை, ஸ்டெம் செல் தொழில்நுட்பம், மருத்துவ சுற்றுலா. அறிவியல் மற்றும் தொழில்நுட்பத்தில் இந்தியர்களின் சாதனைகள், சமீபத்திய கண்டுபிடிப்புகள்.'),
    ('Main — Paper III, Unit III: Tamil Society — Its Culture and Heritage',
     'தமிழ் சமூகம்: தோற்றம் மற்றும் விரிவாக்கம். கலை மற்றும் கலாச்சாரம்: இலக்கியம், இசை, திரைப்படம், நாடகம், கட்டிடக்கலை, சிற்பம், ஓவியம் மற்றும் நாட்டுப்புறக் கலைகள். சங்க காலம் முதல் இன்று வரை தமிழ்நாட்டின் சமூக-பொருளாதார வரலாறு. தமிழ்நாட்டில் பகுத்தறிவுவாத மற்றும் திராவிட இயக்கங்களின் வளர்ச்சி. இக்காலத் தமிழர்களின் சமூக மற்றும் கலாச்சார வாழ்க்கை: சாதி, மதம், பெண்கள், அரசியல், கல்வி, பொருளாதாரம், வணிகம் மற்றும் பிற நாடுகளுடனான உறவு. தமிழும் பிற துறைகளும்: ஊடகம், கணினி.'),
    ('Main — Paper IV, Unit I: Geography of India with Special Reference to Tamil Nadu',
     'இருப்பிடம், இயற்பியல் அம்சங்கள், முக்கிய ஆறுகள், வானிலை மற்றும் காலநிலை, பருவமழை, மழையளவு, இயற்கை வளங்கள்: மண், நீர், காடு, தாதுக்கள், வனவிலங்குகள், வேளாண் முறைகள், கால்நடை, மீன்வளம், தொழில்கள். சமூக-கலாச்சார புவியியல், மக்கள்தொகை வளர்ச்சி, அடர்த்தி மற்றும் பரவல், இன, மொழியியல் மற்றும் முக்கிய பழங்குடியினர். கடல்சார் அறிவியல்: இந்திய மகா சமுத்திரம், அரேபியக் கடல் மற்றும் வங்காள விரிகுடாவின் அடித்தள நிவாரண அமைப்புகள். புவியியல் தகவல் தொழில்நுட்பம்: GIS மற்றும் GNSS. வரைபடம்: புவியியல் அடையாளங்கள், இந்தியா மற்றும் அதன் அண்டை நாடுகள்.'),
    ('Main — Paper IV, Unit II: Environment, Biodiversity and Disaster Management',
     'சூழலியல்: சுற்றுச்சூழல் அமைப்பின் அமைப்பு மற்றும் செயல்பாடு, சூழலியல் வளர்ச்சி, உயிரியல் பன்முகத்தன்மை பாதுகாப்பு, வகைகள், இந்தியாவில் ஹாட் ஸ்பாட்கள். நிலைத்த இடங்களில் மற்றும் புற இடங்களில் பாதுகாப்பு. CITES, IUCN மற்றும் உயிரியல் பன்முகத்தன்மை மாநாட்டின் பங்கு. சுற்றுச்சூழல் மாசு மற்றும் மேலாண்மை: காற்று, நீர், மண், வெப்ப மற்றும் ஒலி மாசு. திட மற்றும் ஆபத்தான கழிவு மேலாண்மை. சுற்றுச்சூழல் தாக்க மதிப்பீடு. காலநிலை மாற்றம்: உலகளாவிய சுற்றுச்சூழல் சிக்கல்கள், பருவமழை முறைகளில் மாற்றங்கள், சுற்றுச்சூழல் விளைவுகள் மற்றும் தணிப்பு நடவடிக்கைகள், தூய்மையான மற்றும் பசுமை ஆற்றல். சுற்றுச்சூழல் சட்டங்கள், கொள்கைகள் மற்றும் ஒப்பந்தங்கள், இயற்கை பேரழிவுகள் மற்றும் பேரிடர் மேலாண்மை.'),
    ('Main — Paper IV, Unit III: Indian Economy — Current Economic Trends',
     'இந்திய பொருளாதாரத்தின் அம்சங்கள், மக்கள்தொகை சுயவிவரம், தேசிய வருமானம், மூலதன உருவாக்கம், NEP, நீதி ஆயோக். வேளாண்மை: நில சீர்திருத்தங்கள், பசுமைப் புரட்சி, விலைக் கொள்கை, PDS, மானியம், உணவு பாதுகாப்பு, வேளாண் சந்தை, பயிர் காப்பீடு, கிராமக் கடன், WTO மற்றும் வேளாண்மை. தொழில்துறை: வளர்ச்சி, கொள்கை, பொதுத்துறை, தனியார்மயமாக்கல், தாராளமயமாக்கல், PPP, SEZகள், MSMEகள், இந்தியாவில் தயார். உள்கட்டமைப்பு: போக்குவரத்து, ஆற்றல், சக்தி, தொடர்பு, ஆராய்ச்சி மற்றும் மேம்பாடு. வங்கி மற்றும் நிதி: மத்திய வங்கி, வணிக வங்கி, பங்குச் சந்தை, பணவியல் கொள்கை, RBI. பொது நிதி: வருவாய், GST, நிதி கொள்கை, நிதி ஆணையம். வறுமை, MGNREGA, வேலையின்மை, பணவீக்கம், பாலின சிக்கல்கள். இந்தியாவின் வெளி வணிகம்: BOP, FDI, உலகமயமாக்கல், உலகளாவிய பொருளாதார நெருக்கடி. சர்வதேச நிறுவனங்கள்: IMF, உலக வங்கி, BRICS, SAARC, ASEAN. தமிழ்நாடு பொருளாதாரம்: GSDP, வேளாண்மை, தொழில்துறை, SHGகள், கிராமப்புற பெண்கள் வலிமைப்படுத்தல், கிராமப்புற வறுமை, சுற்றுச்சூழல் சிக்கல்கள், சமீபத்திய அரசாங்க நல திட்டங்கள்.')
  ) AS t(en_title, ct)
  WHERE c.subject_id = v_subject_id AND c.title = t.en_title AND c.content_text_tamil IS NULL;

  RAISE NOTICE 'TNPSC Group 1 seed completed. Subject ID: %', v_subject_id;
END;
$$;
